export const colors = {
  border: {
    love: 'border border-love',
    gold: 'border border-gold',
    rose: 'border border-rose',
    pine: 'border border-pine',
    foam: 'border border-foam',
    iris: 'border border-iris',
  },
  thumb: {
    love: 'scrollbar-thumb-love',
    gold: 'scrollbar-thumb-gold',
    rose: 'scrollbar-thumb-rose',
    pine: 'scrollbar-thumb-pine',
    foam: 'scrollbar-thumb-foam',
    iris: 'scrollbar-thumb-iris',
  },
  bg: {
    love: 'bg-love',
    gold: 'bg-gold',
    rose: 'bg-rose',
    pine: 'bg-pine',
    foam: 'bg-foam',
    iris: 'bg-iris',
  },
  fill: {
    love: 'fill-love',
    gold: 'fill-gold',
    rose: 'fill-rose',
    pine: 'fill-pine',
    foam: 'fill-foam',
    iris: 'fill-iris',
  },
  active: {
    love: 'active:bg-love/80',
    gold: 'active:bg-gold/80',
    rose: 'active:bg-rose/80',
    pine: 'active:bg-pine/80',
    foam: 'active:bg-foam/80',
    iris: 'active:bg-iris/80',
  },
  'focus-within': {
    love: 'focus-within:bg-love/80',
    gold: 'focus-within:bg-gold/80',
    rose: 'focus-within:bg-rose/80',
    pine: 'focus-within:bg-pine/80',
    foam: 'focus-within:bg-foam/80',
    iris: 'focus-within:bg-iris/80',
  },
  text: {
    love: 'text-love',
    gold: 'text-gold',
    rose: 'text-rose',
    pine: 'text-pine',
    foam: 'text-foam',
    iris: 'text-iris',
  },
};
